name: GitAccountSwitcher

options:
  bundleIdPrefix: com.gitaccountswitcher
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES

targets:
  GitAccountSwitcher:
    type: application
    platform: macOS

    sources:
      - path: GitAccountSwitcher
        excludes:
          - "*.md"
          - "build"
          - "*.xcodeproj"
          - "DerivedData"

    settings:
      base:
        PRODUCT_NAME: GitAccountSwitcher
        PRODUCT_BUNDLE_IDENTIFIER: com.gitaccountswitcher.app
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: GitAccountSwitcher/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: "Git Account Switcher"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024. All rights reserved."
        CODE_SIGN_ENTITLEMENTS: GitAccountSwitcher/GitAccountSwitcher.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"

      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"

      release:
        SWIFT_COMPILATION_MODE: wholemodule
